name: release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  build:
    name: build-${{ matrix.label }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            label: linux-x86_64
            arch: x86_64
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -e . pyinstaller
          python -m pip install 'textual>=0.60'
          python -m pip install 'langchain>=0.1.0' 'langchain-openai>=0.1.0' 'langchain-anthropic>=0.1.0' 'langchain-community>=0.1.0' 'langchain-core>=0.1.0'
      - name: Build binary (Linux)
        run: |
          set -euo pipefail
          # Create a launcher script that PyInstaller can handle
          cat > launcher.py << 'EOF'
          import sys
          from cyberzard.cli import app
          if __name__ == "__main__":
              app()
          EOF
          pyinstaller --onefile --name "cyberzard-linux-x86_64" \
            --hidden-import=textual \
            --hidden-import=textual.app \
            --hidden-import=textual.widgets \
            --hidden-import=textual.reactive \
            --hidden-import=cyberzard.tui \
            --hidden-import=langchain \
            --hidden-import=langchain.agents \
            --hidden-import=langchain_openai \
            --hidden-import=langchain_anthropic \
            --hidden-import=langchain_community \
            --hidden-import=langchain_core \
            --collect-all=langchain \
            --collect-all=langchain_openai \
            --collect-all=langchain_anthropic \
            --collect-all=langchain_community \
            --collect-all=langchain_core \
            launcher.py
      - name: Smoke test binary
        run: |
          set -euo pipefail
          NAME_BASE="cyberzard-linux-x86_64"
          BIN="dist/$NAME_BASE"
          echo "Testing $BIN"
          [[ -f "$BIN" ]] || (echo "Missing $BIN" && ls -la dist && exit 1)
          chmod +x "$BIN"
          "$BIN" --help >/dev/null
          "$BIN" version
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: dist-${{ runner.os }}
          path: dist/*

  publish:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          path: dist
      - name: Flatten artifacts
        run: |
          mkdir -p upload
          find dist -type f -maxdepth 2 -exec cp {} upload/ \;
      - name: Generate checksums
        run: |
          cd upload
          shopt -s nullglob
          for f in cyberzard-*; do
            sha256sum "$f" >> checksums.txt
          done
          cat checksums.txt
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          name: ${{ github.ref_name }}
          draft: false
          prerelease: false
          files: |
            upload/cyberzard-*
            upload/checksums.txt
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
